### ISSUE TITLE
README.md - Getting Started 

### ISSUE THREAD

**Issue by d023604** [SAP-samples/odata-basics-handsonsapdev#12]
In the README.md, section Getting started, the user is advised:

After cloning this repo and moving into the repo top directory, first deploy to a local SQLite database and then start the service up:

```bash
cds deploy --to sqlite
cds run
```
May I suggest adding npm install to the bash commands, so the required packages are installed?

**Comment by qmacro** [comment]
Thanks, nice addition 👍
