### ISSUE TITLE
Modelling and handling of temporal data in OData and CAP

### ISSUE THREAD

**Issue by qmacro** [SAP-samples/odata-basics-handsonsapdev#4]

**Comment by d023604** [comment]
You might find the comment from https://people.sap.com/olena_ to Gregor Wolf of interest. 

_ We are currently planning to implement support for [OData Temporal Extension](https://docs.oasis-open.org/odata/odata-temporal-ext/v4.0/odata-temporal-ext-v4.0.html), but there is still no timeline on this. Until then there is no alternative to sap-valid-from and sap-valid-to in temporal data. _.

See https://answers.sap.com/questions/13639744/warning-query-options-sap-valid-from-and-sap-valid.html  for context.

**Comment by qmacro** [comment]
Thanks Andrew.
